### ISSUE TITLE
web-ui constantly refreshed with auth error

### ISSUE THREAD

**Issue by timlaverty** [Azure/reverse-proxy-dotnet#13] opened 2017-09-21 17:11 UTC
- [x ] Bug

# Description
Auth refreshes the screen every ~1 second.

alternating from the site URL 

...to this URL:
```https://<mysiteURL>/#error=access_denied&error_description=AADSTS65005%3a+Invalid+resource.+The+client+has+requested+access+to+a+resource+which+is+not+listed+in+the+requested+permissions+in+the+client%27s+application+registration.+Client+app+ID%3a+c275c391-7e50-43d5-99da-436393eeff15.+Resource+value+from+request%3a+.+Resource+app+ID%3a+00000002-0000-0000-c000-000000000000.+List+of+valid+resources+from+app+registration%3a+.%0d%0aTrace+ID%3a+3ce2a558-af64-44a1-9aeb-b4bad9353600%0d%0aCorrelation+ID%3a+bb8fe161-a363-4ca9-8191-dfa2fef1d414%0d%0aTimestamp%3a+2017-09-21+17%3a06%3a35Z&state=c535c1e0-3165-4430-ad35-c9087c030ec7```

...and back to the site URL.

# Steps to reproduce
- new basic dotnet deployment from cli

**Comment by dluc** [comment] 2017-09-22 23:35
Root cause will be addressed by https://github.com/Azure/pcs-cli/issues/143

**Closed by dluc** 2017-09-22 23:35 UTC
Labels: bug, MVP, P1, triaged
